version: '3.5'

services:
  app:
    build:
      context: .
    volumes:
    - .:/app
    - /home/locoadmin/webhost/:/webhost
    - galileo_sese_asu_edu_cert.cer --keyfile=/home/locoadmin/webhost/galileo.key
    environment:
      - DEBUG=1
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
